version: '3.7'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: countries_prueba
        ports:
            - '3306'
