<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLNFChP7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLNFChP7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLNFChP7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLNFChP7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLNFChP7\App_KernelDevDebugContainer([
    'container.build_hash' => 'LNFChP7',
    'container.build_id' => 'a8b6532f',
    'container.build_time' => 1656770405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLNFChP7');
