<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnGIc9K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnGIc9K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCnGIc9K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCnGIc9K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCnGIc9K\App_KernelDevDebugContainer([
    'container.build_hash' => 'CnGIc9K',
    'container.build_id' => '04925f58',
    'container.build_time' => 1656801429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnGIc9K');
