<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_index_indexnolocale' => [[], ['_controller' => 'App\\Controller\\IndexController::indexNoLocale'], [], [['text', '/']], [], [], []],
    'homepage' => [['_locale'], ['_controller' => 'App\\Controller\\IndexController::index'], ['_locale' => 'en|es'], [['text', '/'], ['variable', '/', 'en|es', '_locale', true]], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
];
